---
title: "ESTIMATING PARAMETERS FROM REAL DATA"
author: "An Tran"
date: "2025-10-30"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(readxl)
library(ggplot2)
library(MASS)
```

## Dengue data

```{r, echo=FALSE} 
df_sxh <- read_xlsx("Data/data.xlsx", sheet = "sxh_full")
```

```{r}
## Năm 2016
sxh2016 <- subset(df_sxh, nam == "2016")
m_sxh16 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2016)

theta <- 5.918 # m_sxh16$coefficients[1]
beta <- -0.002 # m_sxh16$coefficients[2]
gamma1 <- 0.765 # m_sxh16$coefficients[3]
gamma2 <- -0.404 # m_sxh16$coefficients[4]
phi <- 24.663 # m_sxh16$theta
```

```{r}
## Năm 2017
sxh2017 <- subset(df_sxh, nam == "2017")
m_sxh17 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2017)

theta <- 6.780
beta <- -0.004
gamma1 <- -0.070
gamma2 <- -0.630
phi <- 36.391
```

```{r}
## Năm 2018
sxh2018 <- subset(df_sxh, nam == "2018")
m_sxh18 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2018)

theta <- 4.686
beta <- 0.014
gamma1 <- 0.433
gamma2 <- -0.717
phi <- 42.386
```

```{r}
## Năm 2020
sxh2020 <- subset(df_sxh, nam == "2020")
m_sxh20 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2020)

theta <- 7.496
beta <- -0.008
gamma1 <- 0.624
gamma2 <- -0.989
phi <- 36.748
```

```{r}
theta <- c(5.918, 6.780, 4.686, 7.496)
beta <- c(-0.002, -0.004, 0.014, -0.008)
gamma1 <- c(0.765, -0.070, 0.433, 0.624)
gamma2 <- c(-0.404, -0.630, -0.717, -0.989)
phi <- c(24.663, 36.391, 42.386, 36.748)
year <- c(2016, 2017, 2018, 2020)

dff <- data.frame(year, theta, beta, gamma1, gamma2, phi)

knitr::kable(dff)
```

## HFMD data

```{r}
df_tcm <- read_xlsx("Data/data.xlsx", sheet = "tcm_full")
```

```{r}
# Năm 2016
tcm2016 <- subset(df_tcm, nam == "2016")
m_tcm16 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2016)

theta <- 4.229
beta <- 0.016
gamma1 <- -0.170
gamma2 <- -0.007
phi <- 15.109
```

```{r}
## Năm 2017
tcm2017 <- subset(df_tcm, nam == "2017")
m_tcm17 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2017)

theta <- 5.488
beta <- 0.008
gamma1 <- -0.520
gamma2 <- -0.708
phi <- 35.945
```

```{r}
## Năm 2019
tcm2019 <- subset(df_tcm, nam == "2019")
m_tcm19 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2019)

theta <- 5.999
beta <- -0.0002
gamma1 <- 0.059
gamma2 <- -1.110
phi <- 9.736
```

```{r}
## Năm 2020
tcm2020 <- subset(df_tcm, nam == "2020")
m_tcm20 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2020)

theta <- 5.286
beta <- -0.001
gamma1 <- 0.721
gamma2 <- -2.065
phi <- 5.920
```

```{r}
## Năm 2022
tcm2022 <- subset(df_tcm, nam == "2022")
m_tcm22 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2022)

theta <- -25.757
beta <- 0.130
gamma1 <- -2.124
gamma2 <- -0.469
phi <- 3.418
```

```{r}
theta <- c(4.229, 5.488, 5.999, 5.286, -25.757)
beta <- c(0.016, 0.008, -0.0002, -0.001, 0.130)
gamma1 <- c(-0.170, -0.520, 0.059, 0.721, -2.124)
gamma2 <- c(-0.007, -0.708, -1.110, -2.065, -0.469)
phi <- c(15.109, 35.945, 9.736, 5.920, 3.418)
year <- c(2016, 2017, 2019, 2020, 2022)

dff <- data.frame(year, theta, beta, gamma1, gamma2, phi)

knitr::kable(dff)
```