---
title: "Đánh giá năm dịch và năm không dịch"
format: docx

---

```{r}
#| message: false
#| warning: false

source("functions.R")
```

## Load data

```{r}
sxh_tp <- load_data("https://docs.google.com/spreadsheets/d/1TefEasY2RvEZcJvYqRwCXOg8e4aFtaf_0v5Gc6ftr-o/edit?usp=sharing",
                     sheet = "sxh_tp")

sxh_qh <- load_data("https://docs.google.com/spreadsheets/d/1TefEasY2RvEZcJvYqRwCXOg8e4aFtaf_0v5Gc6ftr-o/edit?usp=sharing",
                     sheet = "sxh_qh")

tcm_tp <- load_data("https://docs.google.com/spreadsheets/d/1TefEasY2RvEZcJvYqRwCXOg8e4aFtaf_0v5Gc6ftr-o/edit?usp=sharing",
                     sheet = "tcm_tp")

tcm_qh <- load_data("https://docs.google.com/spreadsheets/d/1TefEasY2RvEZcJvYqRwCXOg8e4aFtaf_0v5Gc6ftr-o/edit?usp=sharing",
                     sheet = "tcm_qh")

## Population density
pop <- load_data("https://docs.google.com/spreadsheets/d/1sQ1bWkLqF136PO5MfjtRCB9q0d_Krew54AM7sX69Pr4/edit?usp=sharing", sheet = "Tổng")
```

```{r}
# Load mấy package cần thiết
library(ggplot2)
library(patchwork)
library(dplyr)

# 1. Tiền xử lý: Tạo cột thời gian liên tục từ year và week
# (Dùng %Y-%U-%u để R hiểu là Năm - Tuần thứ mấy - Ngày thứ 2 trong tuần)
sxh_tp <- sxh_tp %>% 
  mutate(date = as.Date(paste(year, week, 1, sep="-"), "%Y-%U-%u"))

tcm_tp <- tcm_tp %>% 
  mutate(date = as.Date(paste(year, week, 1, sep="-"), "%Y-%U-%u"))

# 2. Vẽ biểu đồ Dengue fever (SXH)
p1 <- ggplot(sxh_tp, aes(x = date, y = cases)) +
  geom_line(color = "#00468B", linewidth = 0.8) + # Màu xanh chuẩn khoa học
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  labs(x = "Year", y = "Cases") + # Có thể đổi sang tiếng Việt nếu muốn
  theme_classic() +
  theme(
    plot.title = element_blank(),           # Bỏ title
    axis.title = element_text(size = 14),   # Size chữ trục
    axis.text = element_text(size = 14)     # Size chữ giá trị
  )

# 3. Vẽ biểu đồ Hand-Foot-Mouth Disease (TCM)
p2 <- ggplot(tcm_tp, aes(x = date, y = cases)) +
  geom_line(color = "#ED0000", linewidth = 0.8) + # Màu đỏ chuẩn khoa học
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  labs(x = "Year", y = "Cases") +
  theme_classic() +
  theme(
    plot.title = element_blank(),           # Bỏ title
    axis.title = element_text(size = 14),   
    axis.text = element_text(size = 14)     
  )

# 4. Nối 2 biểu đồ bằng patchwork và gắn tag (A), (B)
final_plot <- p1 / p2 + 
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 16, face = "bold")) # Chữ A, B in đậm xíu cho ngầu

# Hiện kết quả
final_plot

# Nếu muốn lưu ảnh nét căng 300dpi để nộp báo:
ggsave("dengue_hfmd_plot.png", final_plot, width = 10, height = 8, dpi = 300)

```

## Dengue - City

```{r}
#| message: false
#| warning: false
rs2018 <- run_algos_city(sxh_tp, 2018)
rs2019 <- run_algos_city(sxh_tp, 2019)
rs2020 <- run_algos_city(sxh_tp, 2020)
rs2022 <- run_algos_city(sxh_tp, 2022)
rs2023 <- run_algos_city(sxh_tp, 2023)
rs2024 <- run_algos_city(sxh_tp, 2024)

all_res_dengue <- bind_rows(rs2018, rs2019, rs2020, rs2022, rs2023, rs2024)

summary_alarms <- all_res_dengue %>%
  pivot_longer(
    cols = starts_with("ub_"), 
    names_to = "algorithm", 
    values_to = "threshold"
  ) %>%
  mutate(is_alarm = if_else(!is.na(threshold) & cases >= threshold, 1, 0)) %>%
  group_by(year, algorithm) %>%
  summarise(total_weeks_alarm = sum(is_alarm), .groups = "drop") %>%
  mutate(algorithm = str_remove(algorithm, "ub_")) %>%
  pivot_wider(
    names_from = algorithm, 
    values_from = total_weeks_alarm
  )  
```

```{r}
#| message: false
#| warning: false
all_res_long <- all_res_dengue %>% 
  pivot_longer(cols = 5:23,
               values_to = "values",
               names_to = "variables")

labels <- c(
  "ub_cdc" = "CDC",
  "ub_rki1" = "RKI1",
  "ub_rki2" = "RKI2",
  "ub_bayes1" = "Bayes1",
  "ub_bayes2" = "Bayes2",
  "ub_far_old" = "Farrington",
  "ub_far_flex" = "Farrington Flexible",
  "ub_earsC1" = "EARS C1",
  "ub_earsC2" = "EARS C2",
  "ub_earsC3" = "EARS C3",
  "ub_glrnb" = "GLR Negbin",
  "ub_glrpois" = "GLR Poisson",
  "ub_cusum" = "CUSUM",
  "ub_cusum_rossi" = "CUSUM Rossi",
  "ub_cusum_rossiGLM" = "CUSUM Rossi fit GLM",
  "ub_cusum_negbin" = "CUSUM Negbin",
  "ub_cusum_negbinGLM" = "CUSUM Negbin fit GLM",
  "ub_serfling" = "Serfling",
  "ub_mem" = "MEM"
)

group_A <- c("ub_cdc", "ub_mem", "ub_serfling")

pdf("charts_dengue.pdf", width = 15, height = 12)

unique_years <- unique(all_res_long$year)

for (y in unique_years) {
  
  data_plot <- all_res_long %>% filter(year == y)
  
  # --- Plot A ---
  p_A <- data_plot %>% 
    filter(variables %in% group_A) %>% 
    ggplot(aes(x = week)) +
    geom_col(aes(y = cases, fill = "Cases"), width = 1) +
    geom_line(aes(y = values, color = "Threshold")) +
    facet_wrap(~variables, labeller = labeller(variables = labels), scales = "free_y", ncol = 3) +
    scale_fill_manual(name = "", values = c("Cases" = "grey80")) +
    scale_color_manual(name = "", values = c("Threshold" = "red")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Weeks", y = "Cases", title = "(A) Not using current year")
  
  # --- Plot B ---
  p_B <- data_plot %>% 
    filter(!variables %in% group_A) %>% 
    ggplot(aes(x = week)) +
    geom_col(aes(y = cases, fill = "Cases"), width = 1) +
    geom_line(aes(y = values, color = "Threshold")) +
    facet_wrap(~variables, labeller = labeller(variables = labels), scales = "free_y", ncol = 4) +
    scale_fill_manual(name = "", values = c("Cases" = "grey80")) +
    scale_color_manual(name = "", values = c("Threshold" = "red")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Weeks", y = "Cases", title = "(B) Using current year")
  
  # --- Combine A and B ---
  p_combined <- (p_A / p_B) + 
    plot_layout(heights = c(1, 4), guides = "collect") + 
    plot_annotation(
      title = paste("Year:", y),
      theme = theme(legend.position = "bottom",
                    plot.title = element_text(size = 16, face = "bold"))
    )
  
  print(p_combined)
}

dev.off()
```

## Dengue - Districts

```{r}
d2018 <- run_algos_by_district(sxh_qh, 2018)
d2019 <- run_algos_by_district(sxh_qh, 2019)
d2020 <- run_algos_by_district(sxh_qh, 2020)
d2022 <- run_algos_by_district(sxh_qh, 2022)
d2023 <- run_algos_by_district(sxh_qh, 2023)
d2024 <- run_algos_by_district(sxh_qh, 2024)

all_res_districts <- bind_rows(d2018, d2019, d2020, d2022, d2023, d2024)

summary_alarms_districts <- all_res_districts %>%
  pivot_longer(
    cols = starts_with("ub_"), 
    names_to = "algorithm", 
    values_to = "threshold"
  ) %>%
  mutate(is_alarm = if_else(!is.na(threshold) & cases >= threshold, 1, 0)) %>%
  group_by(year, districts, algorithm) %>% 
  summarise(total_weeks_alarm = sum(is_alarm, na.rm = TRUE), .groups = "drop")

summary_alarms_districts <- summary_alarms_districts %>% 
    mutate(districts = recode(districts,
    "bc"   = "Bình Chánh",
    "bt"   = "Bình Thạnh",
    "bta"  = "Bình Tân",
    "cc"   = "Củ Chi",
    "cg"   = "Cần Giờ",
    "gv"   = "Gò Vấp",
    "hm"   = "Hóc Môn",
    "nb"   = "Nhà Bè",
    "pn"   = "Phú Nhuận",
    "q1"   = "Quận 1",
    "q10"  = "Quận 10",
    "q11"  = "Quận 11",
    "q12"  = "Quận 12",
    "q3"   = "Quận 3",
    "q4"   = "Quận 4",
    "q5"   = "Quận 5",
    "q6"   = "Quận 6",
    "q7"   = "Quận 7",
    "q8"   = "Quận 8",
    "tb"   = "Tân Bình",
    "tp"   = "Tân Phú",
    "tptd" = "Thành phố Thủ Đức"
  ))
```

```{r}
pop_2018 <- pop %>% 
  filter(year == 2019) %>% 
  mutate(year = 2018)

pop_2022 <- pop %>% 
  filter(year == 2023) %>% 
  mutate(year = 2022)

pop_final <- bind_rows(pop, pop_2018, pop_2022) %>% 
  arrange(districts, year)
```

```{r}
#| message: false
#| warning: false
df_final <- summary_alarms_districts %>%
  left_join(pop_final, by = c("year", "districts"))

df_final <- df_final %>%
  mutate(dist_abbr = case_match(districts,
  
    "Quận 1" ~ "Q1", "Quận 3" ~ "Q3", "Quận 4" ~ "Q4", 
    "Quận 5" ~ "Q5", "Quận 6" ~ "Q6", "Quận 7" ~ "Q7", 
    "Quận 8" ~ "Q8", "Quận 10" ~ "Q10", "Quận 11" ~ "Q11", 
    "Quận 12" ~ "Q12",
    
    "Bình Thạnh" ~ "BT",
    "Bình Tân"   ~ "BTA",
    "Gò Vấp"     ~ "GV",
    "Phú Nhuận"  ~ "PN",
    "Tân Bình"   ~ "TB",
    "Tân Phú"    ~ "TP",
    "Thành phố Thủ Đức" ~ "TD",
    
    # District Group
    "Bình Chánh" ~ "BC",
    "Cần Giờ"    ~ "CG",
    "Củ Chi"     ~ "CC",
    "Hóc Môn"    ~ "HM",
    "Nhà Bè"     ~ "NB"))

group_A <- c("ub_cdc", "ub_mem", "ub_serfling")

pdf("charts_dengue_districts_scatter.pdf", width = 15, height = 12)

unique_years <- unique(df_final$year)

for (y in unique_years) {
  
  data_plot <- df_final %>% filter(year == y)
  
  p_A <- data_plot %>% 
    filter(algorithm %in% group_A) %>% 
    ggplot(aes(x = popd, y = total_weeks_alarm)) +
    geom_point(aes(color = "Districts"), alpha = 0.7, size = 1.5) +
    geom_text_repel(aes(label = dist_abbr), size = 3, box.padding = 0.5, 
                    max.overlaps = Inf, segment.size = 0.2, segment.color = "grey70", segment.alpha = 0.6) +
    facet_wrap(~algorithm, scales = "fixed", labeller = labeller(algorithm = labels), ncol = 3) + 
    scale_x_log10(labels = comma) +
    scale_color_manual(name = "", values = c("Districts" = "firebrick")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Population Density (Log scale)", y = "Alarm weeks", title = "(A) Not using current year")

  p_B <- data_plot %>% 
    filter(!algorithm %in% group_A) %>% 
    ggplot(aes(x = popd, y = total_weeks_alarm)) +
    geom_point(aes(color = "Districts"), alpha = 0.7, size = 1.5) +
    geom_text_repel(aes(label = dist_abbr), size = 3, box.padding = 0.5, 
                    max.overlaps = Inf, segment.size = 0.2, segment.color = "grey70", segment.alpha = 0.6) +
    facet_wrap(~algorithm, scales = "fixed", labeller = labeller(algorithm = labels), ncol = 4) + 
    scale_x_log10(labels = comma) +
    scale_color_manual(name = "", values = c("Districts" = "firebrick")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Population Density (Log scale)", y = "Alarm weeks", title = "(B) Using current year")

  p_combined <- (p_A / p_B) + 
    plot_layout(heights = c(1, 4), guides = "collect") + 
    plot_annotation(
      title = paste("Year:", y),
      theme = theme(legend.position = "bottom",
                    plot.title = element_text(size = 16, face = "bold"))
    )
  
  print(p_combined)
}

dev.off()
```

```{r}
#| message: false
#| warning: false
dist_levels <- df_final %>% 
  filter(year == 2019) %>% 
  arrange(popd) %>%         
  pull(dist_abbr) %>%       
  unique()

df_final$dist_abbr <- factor(df_final$dist_abbr, levels = dist_levels)

pdf("charts_dengue_heatmap.pdf", width = 15, height = 12)

unique_years <- unique(df_final$year)

for (y in unique_years) {
  
  data_plot <- df_final %>% filter(year == y)
  
  # Calculate max limit for the entire year to keep color scales identical
  max_alarm <- max(data_plot$total_weeks_alarm, na.rm = TRUE)
  
  p_A <- data_plot %>% filter(algorithm %in% group_A) %>% 
    ggplot(aes(x = dist_abbr, y = algorithm)) +
    geom_tile(aes(fill = total_weeks_alarm), color = "white", linewidth = 0.5) +
    geom_text(aes(label = total_weeks_alarm), size = 3, color = "black") +
    scale_fill_gradient(low = "#ebf5fb", high = "#c0392b", na.value = "grey90", limits = c(0, max_alarm)) +
    scale_y_discrete(labels = labels) +
    theme_minimal() +
    labs(x = "", y = "", title = "(A) Not using current year", fill = "Alarm weeks") +
    theme(axis.text.x = element_blank(), 
          axis.text.y = element_text(size = 11, color = "black"),
          panel.grid = element_blank())

  p_B <- data_plot %>% filter(!algorithm %in% group_A) %>% 
    ggplot(aes(x = dist_abbr, y = algorithm)) +
    geom_tile(aes(fill = total_weeks_alarm), color = "white", linewidth = 0.5) +
    geom_text(aes(label = total_weeks_alarm), size = 3, color = "black") +
    scale_fill_gradient(low = "#ebf5fb", high = "#c0392b", na.value = "grey90", limits = c(0, max_alarm)) +
    scale_y_discrete(labels = labels) +
    theme_minimal() +
    labs(x = "Districts (Low to High Population Density)", y = "", title = "(B) Using current year", fill = "Alarm weeks") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 13, color = "black"),
          axis.text.y = element_text(size = 11, color = "black"),
          panel.grid = element_blank())

  p_combined <- (p_A / p_B) + 
    plot_layout(heights = c(1, 4), guides = "collect") + 
    plot_annotation(
      title = paste("Year:", y),
      theme = theme(plot.title = element_text(size = 16, face = "bold"))
    )
  
  print(p_combined)
}

dev.off()
```

## HFMD - City

```{r}
#| message: false
#| warning: false
c2018 <- run_algos_city(tcm_tp, 2018)
c2019 <- run_algos_city(tcm_tp, 2019)
c2020 <- run_algos_city(tcm_tp, 2020)
c2022 <- run_algos_city(tcm_tp, 2022)
c2023 <- run_algos_city(tcm_tp, 2023)
c2024 <- run_algos_city(tcm_tp, 2024)

all_res_hfmd <- bind_rows(c2018, c2019, c2020, c2022, c2023, c2024)

summary_alarms <- all_res %>%
  pivot_longer(
    cols = starts_with("ub_"), 
    names_to = "algorithm", 
    values_to = "threshold"
  ) %>%
  mutate(is_alarm = if_else(!is.na(threshold) & cases >= threshold, 1, 0)) %>%
  group_by(year, algorithm) %>%
  summarise(total_weeks_alarm = sum(is_alarm), .groups = "drop") %>%
  mutate(algorithm = str_remove(algorithm, "ub_")) %>%
  pivot_wider(
    names_from = algorithm, 
    values_from = total_weeks_alarm
  )
```

```{r}
#| message: false
#| warning: false
all_res_long <- all_res %>% 
  pivot_longer(cols = 5:23,
               values_to = "values",
               names_to = "variables")

labels <- c(
  "ub_cdc" = "CDC",
  "ub_rki1" = "RKI1",
  "ub_rki2" = "RKI2",
  "ub_bayes1" = "Bayes1",
  "ub_bayes2" = "Bayes2",
  "ub_far_old" = "Farrington",
  "ub_far_flex" = "Farrington Flexible",
  "ub_earsC1" = "EARS C1",
  "ub_earsC2" = "EARS C2",
  "ub_earsC3" = "EARS C3",
  "ub_glrnb" = "GLR Negbin",
  "ub_glrpois" = "GLR Poisson",
  "ub_cusum" = "CUSUM",
  "ub_cusum_rossi" = "CUSUM Rossi",
  "ub_cusum_rossiGLM" = "CUSUM Rossi fit GLM",
  "ub_cusum_negbin" = "CUSUM Negbin",
  "ub_cusum_negbinGLM" = "CUSUM Negbin fit GLM",
  "ub_serfling" = "Serfling",
  "ub_mem" = "MEM"
)

group_A <- c("ub_cdc", "ub_mem", "ub_serfling")

pdf("charts_hfmd.pdf", width = 15, height = 12)

unique_years <- unique(all_res_long$year)

for (y in unique_years) {
  
  data_plot <- all_res_long %>% filter(year == y)
  
  # --- Plot A ---
  p_A <- data_plot %>% 
    filter(variables %in% group_A) %>% 
    ggplot(aes(x = week)) +
    geom_col(aes(y = cases, fill = "Cases"), width = 1) +
    geom_line(aes(y = values, color = "Threshold")) +
    facet_wrap(~variables, labeller = labeller(variables = labels), scales = "free_y", ncol = 3) +
    scale_fill_manual(name = "", values = c("Cases" = "grey80")) +
    scale_color_manual(name = "", values = c("Threshold" = "red")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Weeks", y = "Cases", title = "(A) Not using current year")
  
  # --- Plot B ---
  p_B <- data_plot %>% 
    filter(!variables %in% group_A) %>% 
    ggplot(aes(x = week)) +
    geom_col(aes(y = cases, fill = "Cases"), width = 1) +
    geom_line(aes(y = values, color = "Threshold")) +
    facet_wrap(~variables, labeller = labeller(variables = labels), scales = "free_y", ncol = 4) +
    scale_fill_manual(name = "", values = c("Cases" = "grey80")) +
    scale_color_manual(name = "", values = c("Threshold" = "red")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Weeks", y = "Cases", title = "(B) Using current year")
  
  # --- Combine A and B ---
  p_combined <- (p_A / p_B) + 
    plot_layout(heights = c(1, 4), guides = "collect") + 
    plot_annotation(
      title = paste("Year:", y),
      theme = theme(legend.position = "bottom",
                    plot.title = element_text(size = 16, face = "bold"))
    )
  
  print(p_combined)
}

dev.off()
```

## HFMD - Districts

```{r}
#| message: false
#| warning: false
d2018 <- run_algos_by_district(tcm_qh, 2018)
d2019 <- run_algos_by_district(tcm_qh, 2019)
d2020 <- run_algos_by_district(tcm_qh, 2020)
d2022 <- run_algos_by_district(tcm_qh, 2022)
d2023 <- run_algos_by_district(tcm_qh, 2023)
d2024 <- run_algos_by_district(tcm_qh, 2024)

all_res_districts <- bind_rows(d2018, d2019, d2020, d2022, d2023, d2024)

summary_alarms_districts <- all_res_districts %>%
  pivot_longer(
    cols = starts_with("ub_"), 
    names_to = "algorithm", 
    values_to = "threshold"
  ) %>%
  mutate(is_alarm = if_else(!is.na(threshold) & cases >= threshold, 1, 0)) %>%
  group_by(year, districts, algorithm) %>% 
  summarise(total_weeks_alarm = sum(is_alarm, na.rm = TRUE), .groups = "drop")

summary_alarms_districts <- summary_alarms_districts %>% 
    mutate(districts = recode(districts,
    "bc"   = "Bình Chánh",
    "bt"   = "Bình Thạnh",
    "bta"  = "Bình Tân",
    "cc"   = "Củ Chi",
    "cg"   = "Cần Giờ",
    "gv"   = "Gò Vấp",
    "hm"   = "Hóc Môn",
    "nb"   = "Nhà Bè",
    "pn"   = "Phú Nhuận",
    "q1"   = "Quận 1",
    "q10"  = "Quận 10",
    "q11"  = "Quận 11",
    "q12"  = "Quận 12",
    "q3"   = "Quận 3",
    "q4"   = "Quận 4",
    "q5"   = "Quận 5",
    "q6"   = "Quận 6",
    "q7"   = "Quận 7",
    "q8"   = "Quận 8",
    "tb"   = "Tân Bình",
    "tp"   = "Tân Phú",
    "tptd" = "Thành phố Thủ Đức"
  ))
```

```{r}
pop_2018 <- pop %>% 
  filter(year == 2019) %>% 
  mutate(year = 2018)

pop_2022 <- pop %>% 
  filter(year == 2023) %>% 
  mutate(year = 2022)

pop_final <- bind_rows(pop, pop_2018, pop_2022) %>% 
  arrange(districts, year)
```

```{r}
#| message: false
#| warning: false
df_final <- summary_alarms_districts %>%
  left_join(pop_final, by = c("year", "districts"))

df_final <- df_final %>%
  mutate(dist_abbr = case_match(districts,
  
    "Quận 1" ~ "Q1", "Quận 3" ~ "Q3", "Quận 4" ~ "Q4", 
    "Quận 5" ~ "Q5", "Quận 6" ~ "Q6", "Quận 7" ~ "Q7", 
    "Quận 8" ~ "Q8", "Quận 10" ~ "Q10", "Quận 11" ~ "Q11", 
    "Quận 12" ~ "Q12",
    
    "Bình Thạnh" ~ "BT",
    "Bình Tân"   ~ "BTA",
    "Gò Vấp"     ~ "GV",
    "Phú Nhuận"  ~ "PN",
    "Tân Bình"   ~ "TB",
    "Tân Phú"    ~ "TP",
    "Thành phố Thủ Đức" ~ "TD",
    
    # Nhóm Huyện
    "Bình Chánh" ~ "BC",
    "Cần Giờ"    ~ "CG",
    "Củ Chi"     ~ "CC",
    "Hóc Môn"    ~ "HM",
    "Nhà Bè"     ~ "NB"))

group_A <- c("ub_cdc", "ub_mem", "ub_serfling")

pdf("hfmd_districts_scatter.pdf", width = 15, height = 12)

unique_years <- unique(df_final$year)

for (y in unique_years) {
  
  data_plot <- df_final %>% filter(year == y)
  
  p_A <- data_plot %>% 
    filter(algorithm %in% group_A) %>% 
    ggplot(aes(x = popd, y = total_weeks_alarm)) +
    geom_point(aes(color = "Districts"), alpha = 0.7, size = 1.5) +
    geom_text_repel(aes(label = dist_abbr), size = 3, box.padding = 0.5, 
                    max.overlaps = Inf, segment.size = 0.2, segment.color = "grey70", segment.alpha = 0.6) +
    facet_wrap(~algorithm, scales = "fixed", labeller = labeller(algorithm = labels), ncol = 3) + 
    scale_x_log10(labels = comma) +
    scale_color_manual(name = "", values = c("Districts" = "firebrick")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Population Density (Log scale)", y = "Alarm weeks", title = "(A) Not using current year")

  p_B <- data_plot %>% 
    filter(!algorithm %in% group_A) %>% 
    ggplot(aes(x = popd, y = total_weeks_alarm)) +
    geom_point(aes(color = "Districts"), alpha = 0.7, size = 1.5) +
    geom_text_repel(aes(label = dist_abbr), size = 3, box.padding = 0.5, 
                    max.overlaps = Inf, segment.size = 0.2, segment.color = "grey70", segment.alpha = 0.6) +
    facet_wrap(~algorithm, scales = "fixed", labeller = labeller(algorithm = labels), ncol = 4) + 
    scale_x_log10(labels = comma) +
    scale_color_manual(name = "", values = c("Districts" = "firebrick")) +
    theme_bw() +
    theme(strip.background = element_rect(fill = "lightblue"),
          axis.text = element_text(color = "black")) +
    labs(x = "Population Density (Log scale)", y = "Alarm weeks", title = "(B) Using current year")

  p_combined <- (p_A / p_B) + 
    plot_layout(heights = c(1, 4), guides = "collect") + 
    plot_annotation(
      title = paste("Year:", y),
      theme = theme(legend.position = "bottom",
                    plot.title = element_text(size = 16, face = "bold"))
    )
  
  print(p_combined)
}

dev.off()
```

```{r}
#| message: false
#| warning: false
dist_levels <- df_final %>% 
  filter(year == 2019) %>% 
  arrange(popd) %>%         
  pull(dist_abbr) %>%       
  unique()

df_final$dist_abbr <- factor(df_final$dist_abbr, levels = dist_levels)

pdf("hfmd_districts_heatmap.pdf", width = 15, height = 12)

unique_years <- unique(df_final$year)

for (y in unique_years) {
  
  data_plot <- df_final %>% filter(year == y)
  
  # Calculate max limit for the entire year to keep color scales identical
  max_alarm <- max(data_plot$total_weeks_alarm, na.rm = TRUE)
  
  p_A <- data_plot %>% filter(algorithm %in% group_A) %>% 
    ggplot(aes(x = dist_abbr, y = algorithm)) +
    geom_tile(aes(fill = total_weeks_alarm), color = "white", linewidth = 0.5) +
    geom_text(aes(label = total_weeks_alarm), size = 3, color = "black") +
    scale_fill_gradient(low = "#ebf5fb", high = "#c0392b", na.value = "grey90", limits = c(0, max_alarm)) +
    scale_y_discrete(labels = labels) +
    theme_minimal() +
    labs(x = "", y = "", title = "(A) Not using current year", fill = "Alarm weeks") +
    theme(axis.text.x = element_blank(), 
          axis.text.y = element_text(size = 11, color = "black"),
          panel.grid = element_blank())

  p_B <- data_plot %>% filter(!algorithm %in% group_A) %>% 
    ggplot(aes(x = dist_abbr, y = algorithm)) +
    geom_tile(aes(fill = total_weeks_alarm), color = "white", linewidth = 0.5) +
    geom_text(aes(label = total_weeks_alarm), size = 3, color = "black") +
    scale_fill_gradient(low = "#ebf5fb", high = "#c0392b", na.value = "grey90", limits = c(0, max_alarm)) +
    scale_y_discrete(labels = labels) +
    theme_minimal() +
    labs(x = "Districts (Low to High Population Density)", y = "", title = "(B) Using current year", fill = "Alarm weeks") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 13, color = "black"),
          axis.text.y = element_text(size = 11, color = "black"),
          panel.grid = element_blank())

  p_combined <- (p_A / p_B) + 
    plot_layout(heights = c(1, 4), guides = "collect") + 
    plot_annotation(
      title = paste("Year:", y),
      theme = theme(plot.title = element_text(size = 16, face = "bold"))
    )
  
  print(p_combined)
}

dev.off()
```

## Epidemic curve of districts

```{r}
# ---------------------------------------------------------
# 1. TIỀN XỬ LÝ DỮ LIỆU CẤP QUẬN
# ---------------------------------------------------------
# Tao viết gọn thành 1 hàm để xài chung cho cả SXH và TCM
clean_district_names <- function(df) {
  df %>%
    # Tạo cột thời gian liên tục y chang cấp thành phố
    mutate(date = as.Date(paste(year, week, 1, sep="-"), "%Y-%U-%u")) %>%
    # Đổi mã quận thành tên đàng hoàng để hiển thị trên Facet cho đẹp
    mutate(districts = case_match(districts,
      "q1" ~ "Q1", "q3" ~ "Q3", "q4" ~ "Q4",
      "q5" ~ "Q5", "q6" ~ "Q6", "q7" ~ "Q7",
      "q8" ~ "Q8", "q10" ~ "Q10", "q11" ~ "Q11",
      "q12" ~ "Q12",
      "bt" ~ "BT", "bta" ~ "BTA", "gv" ~ "GV",
      "pn" ~ "PN", "tb" ~ "TB", "tp" ~ "TP",
      "tptd" ~ "TD",
      "bc" ~ "BC", "cg" ~ "CG", "cc" ~ "CC",
      "hm" ~ "HM", "nb" ~ "NB",
      .default = districts
    ))
}

sxh_qh_plot <- clean_district_names(sxh_qh)
tcm_qh_plot <- clean_district_names(tcm_qh)

# ---------------------------------------------------------
# 2. VẼ BIỂU ĐỒ SỐT XUẤT HUYẾT (DENGUE) CẤP QUẬN
# ---------------------------------------------------------
p_sxh_qh <- ggplot(sxh_qh_plot, aes(x = date, y = cases)) +
  geom_line(color = "#00468B", linewidth = 0.5) + # Màu xanh y chang hình A cấp TP
  # Phân mảnh theo quận, xếp 4 cột. Lưu ý: scales = "free_y"
  facet_wrap(~ districts, ncol = 4, scales = "free_y") + 
  scale_x_date(date_breaks = "1 years", date_labels = "%Y") +
  labs(title = "Epidemic curves of Dengue cases by districts",
       x = "Year", y = "Number of Cases") +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#ebf5fb"), # Nền xanh nhạt cho tiêu đề quận
    strip.text = element_text(face = "bold", size = 11, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y = element_text(size = 9),
    plot.title = element_text(face = "bold", size = 14)
  )

# ---------------------------------------------------------
# 3. VẼ BIỂU ĐỒ TAY CHÂN MIỆNG (HFMD) CẤP QUẬN
# ---------------------------------------------------------
p_tcm_qh <- ggplot(tcm_qh_plot, aes(x = date, y = cases)) +
  geom_line(color = "#ED0000", linewidth = 0.5) + # Màu đỏ y chang hình B cấp TP
  facet_wrap(~ districts, ncol = 4, scales = "free_y") +
  scale_x_date(date_breaks = "1 years", date_labels = "%Y") +
  labs(title = "Epidemic curves of HFMD cases by districts",
       x = "Year", y = "Number of Cases") +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#fdedec"), # Nền đỏ nhạt cho tiêu đề quận
    strip.text = element_text(face = "bold", size = 11, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y = element_text(size = 9),
    plot.title = element_text(face = "bold", size = 14)
  )

# ---------------------------------------------------------
# 4. GỘP CHUNG VÀO 1 FILE PDF (2 TRANG)
# ---------------------------------------------------------
# Mở cổng tạo file PDF
pdf("Supp_Combined_Districts.pdf", width = 12, height = 14)

# In trang 1: Dengue
print(p_sxh_qh)

# In trang 2: HFMD
print(p_tcm_qh)

# Đóng cổng lưu file
dev.off()
```

## Re-evaluate by framework

```{r}
###### Dengue ######
####################
framework_real_dengue <- all_res_dengue %>%
  mutate(
    # 1. Xác định tín hiệu đơn lẻ của 2 thuật toán
    cusum_alert = if_else(!is.na(ub_cusum) & cases >= ub_cusum, TRUE, FALSE, missing = FALSE),
    farrington_alert = if_else(!is.na(ub_far_flex) & cases >= ub_far_flex, TRUE, FALSE, missing = FALSE),
    
    # 2. LOGIC PHỄU LỌC TUẦN TỰ (Đúng y như mài dặn)
    Framework_Action = case_when(
      # Tầng 1: Nếu CUSUM không báo -> Chắc chắn là Routine (không thèm xét Farrington)
      cusum_alert == FALSE ~ "Routine Surveillance",
      
      # Tầng 2: CUSUM đã báo, nhưng Farrington KHÔNG báo -> Close Monitoring
      cusum_alert == TRUE & farrington_alert == FALSE ~ "Close Monitoring",
      
      # Tầng 3: Cả CUSUM và Farrington CÙNG BÁO -> Warning (Báo động dịch)
      cusum_alert == TRUE & farrington_alert == TRUE ~ "Warning"
    )
  ) %>%
  # Sắp xếp levels để tô màu cho chuẩn
  mutate(Framework_Action = factor(Framework_Action, 
                                   levels = c("Routine Surveillance", "Close Monitoring", "Warning")))

# Vẽ biểu đồ test thử cho năm 2022 của Dengue
plot1 <- framework_real_dengue %>%
  filter(year == 2022) %>%
  ggplot(aes(x = week, y = cases, fill = Framework_Action)) +
  
  # Dùng geom_col để vẽ biểu đồ dạng cột (Epi-curve)
  # width = 0.8 hoặc 0.9 để các cột có khoảng hở nhẹ nhìn cho đẹp
  geom_col(width = 0.8, alpha = 0.9) +
  
  # Set màu tô (fill) cho từng mức độ
  scale_fill_manual(values = c(
    "Warning" = "red",                # Đỏ sậm
    "Close Monitoring" = "#f39c12",   # Cam
    "Routine Surveillance" = "steelblue"  # Xanh dương
  )) +
  
  theme_bw() +
  labs(
    title = "(A)",
    x = "Week",
    y = "Number of Cases",
    fill = "" # Đổi chữ color thành fill cho đúng legend
  ) +
  theme(
    legend.position = "bottom",
    title = element_text(face = "bold")
  )


###### HFMD ######
####################
framework_real_hfmd <- all_res_hfmd %>%
  mutate(
    # 1. Xác định tín hiệu đơn lẻ của 2 thuật toán
    cusum_alert = if_else(!is.na(ub_cusum) & cases >= ub_cusum, TRUE, FALSE, missing = FALSE),
    farrington_alert = if_else(!is.na(ub_far_flex) & cases >= ub_far_flex, TRUE, FALSE, missing = FALSE),
    
    # 2. LOGIC PHỄU LỌC TUẦN TỰ (Đúng y như mài dặn)
    Framework_Action = case_when(
      # Tầng 1: Nếu CUSUM không báo -> Chắc chắn là Routine (không thèm xét Farrington)
      cusum_alert == FALSE ~ "Routine Surveillance",
      
      # Tầng 2: CUSUM đã báo, nhưng Farrington KHÔNG báo -> Close Monitoring
      cusum_alert == TRUE & farrington_alert == FALSE ~ "Close Monitoring",
      
      # Tầng 3: Cả CUSUM và Farrington CÙNG BÁO -> Warning (Báo động dịch)
      cusum_alert == TRUE & farrington_alert == TRUE ~ "Warning"
    )
  ) %>%
  # Sắp xếp levels để tô màu cho chuẩn
  mutate(Framework_Action = factor(Framework_Action, 
                                   levels = c("Routine Surveillance", "Close Monitoring", "Warning")))

# Vẽ biểu đồ test thử cho năm 2022 của Dengue
plot2 <- framework_real_hfmd %>%
  filter(year == 2023) %>%
  ggplot(aes(x = week, y = cases, fill = Framework_Action)) +
  
  # Dùng geom_col để vẽ biểu đồ dạng cột (Epi-curve)
  # width = 0.8 hoặc 0.9 để các cột có khoảng hở nhẹ nhìn cho đẹp
  geom_col(width = 0.8, alpha = 0.9) +
  
  # Set màu tô (fill) cho từng mức độ
  scale_fill_manual(values = c(
    "Warning" = "red",                # Đỏ sậm
    "Close Monitoring" = "#f39c12",   # Cam
    "Routine Surveillance" = "steelblue"  # Xanh dương
  )) +
  
  theme_bw() +
  labs(
    title = "(B)",
    x = "Week",
    y = "Number of Cases",
    fill = "" # Đổi chữ color thành fill cho đúng legend
  ) +
  theme(
    legend.position = "bottom",
    title = element_text(face = "bold")
  )

final_framework_plot <- (plot1 / plot2) + 
    # guides = "collect" sẽ tự động gom các legend giống nhau thành 1 cái duy nhất
    plot_layout(guides = "collect") & 
    # Đẩy cái legend chung xuống dưới cùng cho đẹp
    theme(legend.position = "bottom",
          axis.text = element_text(size = 14, color = "black"))

# Lưu ảnh chất lượng cao để chèn vào luận văn
ggsave("Framework_Dengue_HFMD_Combined.png", plot = final_framework_plot, width = 11, height = 8, dpi = 300)
```

