---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Ước tính tham số từ dữ liệu thực tế

```{r}
library(readxl)
library(ggplot2)
## time
### training weeks: 1-104 (2 năm)

## Dữ liệu gồm 104 tuần để training
df_sxh <- read_xlsx("Data/data.xlsx", sheet = "sxh_full")
```

```{r}
getmu <- function(t, theta, beta, m, gamma1, gamma2) {
  mu <- sapply(t, FUN = function(x) {
    exp(theta + beta * x + I(m > 0) * (sum(gamma1 * cos(2 * pi * x * (1:m)/ 52)) + sum(gamma2 * sin(2 * pi * x * (1:m)/ 52))))
  })
  return(mu)
}

getsd <- function(mu, phi) {
  sd <- sqrt(mu + ((mu^2)/phi))
  return(sd)
}
```

```{r}
library(MASS)
## Năm 2016
sxh2016 <- subset(df_sxh, nam == "2016")
m_sxh16 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2016)
summary(m_sxh16)
theta <- 5.918
beta <- -0.002
gamma1 <- 0.765
gamma2 <- -0.404
phi <- 24.663

sxh2016$mu <- getmu(t = sxh2016$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = sxh2016, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2017
sxh2017 <- subset(df_sxh, nam == "2017")
m_sxh17 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2017)
summary(m_sxh17)
theta <- 6.780
beta <- -0.004
gamma1 <- -0.070
gamma2 <- -0.630
phi <- 36.391

sxh2017$mu <- getmu(t = sxh2017$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = sxh2017, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2018
sxh2018 <- subset(df_sxh, nam == "2018")
m_sxh18 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2018)
summary(m_sxh18)
theta <- 4.686
beta <- 0.014
gamma1 <- 0.433
gamma2 <- -0.717
phi <- 42.386

sxh2018$mu <- getmu(t = sxh2018$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = sxh2018, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2020
sxh2020 <- subset(df_sxh, nam == "2020")
m_sxh20 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2020)
summary(m_sxh20)
theta <- 7.496
beta <- -0.008
gamma1 <- 0.624
gamma2 <- -0.989
phi <- 36.748

sxh2020$mu <- getmu(t = sxh2020$t, theta = theta, beta = beta, m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = sxh2020, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2023
sxh2023 <- subset(df_sxh, nam == "2023")
m_sxh23 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2023)
summary(m_sxh23)
theta <- 9.973
beta <- -0.017
gamma1 <- 0.439
gamma2 <- -0.546
phi <- 91.831

sxh2023$mu <- getmu(t = sxh2023$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = sxh2023, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2024
sxh2024 <- subset(df_sxh, nam == "2024")
m_sxh24 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = sxh2024)
summary(m_sxh24)
theta <- 7.054
beta <- -0.005
gamma1 <- 0.192
gamma2 <- -0.606
phi <- 61.690

sxh2024$mu <- getmu(t = sxh2024$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = sxh2024, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```


```{r}
df_sxh$mu <- bind_rows(
  sxh2016 %>% dplyr::select(mu),
  sxh2017 %>% dplyr::select(mu),
  sxh2018 %>% dplyr::select(mu),
  sxh2020 %>% dplyr::select(mu),
  sxh2023 %>% dplyr::select(mu),
  sxh2024 %>% dplyr::select(mu)
) %>% pull(mu)

g2 <- ggplot(data = df_sxh, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  geom_vline(xintercept = 52 * c(1:6), col = "red") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 299, by = 26)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw() +
  annotate("text", x = 26, y = 2000, label = "2016") +
  annotate("text", x = 26*3, y = 2000, label = "2017") +
  annotate("text", x = 26*5, y = 2000, label = "2018") +
  annotate("text", x = 26*7, y = 2000, label = "2020") +
  annotate("text", x = 26*9, y = 2000, label = "2023") +
  annotate("text", x = 26*11, y = 2000, label = "2024")
```

```{r}
library(patchwork)
g2 / g1_sxh
```

```{r}
theta <- c(5.918, 6.780, 4.686, 7.496)
beta <- c(-0.002, -0.004, 0.014, -0.008)
gamma1 <- c(0.765, -0.070, 0.433, 0.624)
gamma2 <- c(-0.404, -0.630, -0.717, -0.989)
phi <- c(24.663, 36.391, 42.386, 36.748)
year <- c(2016, 2017, 2018, 2020)

dff <- data.frame(year, theta, beta, gamma1, gamma2, phi)
```