---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Ước tính tham số từ dữ liệu thực tế

```{r}
library(readxl)
library(ggplot2)
## time
### training weeks: 1-104 (2 năm)

## Dữ liệu gồm 104 tuần để training
df_tcm <- read_xlsx("Data/data.xlsx", sheet = "tcm_full")
```

```{r}
getmu <- function(t, theta, beta, m, gamma1, gamma2) {
  mu <- sapply(t, FUN = function(x) {
    exp(theta + beta * x + I(m > 0) * (sum(gamma1 * cos(2 * pi * x * (1:m)/ 52)) + sum(gamma2 * sin(2 * pi * x * (1:m)/ 52))))
  })
  return(mu)
}

getsd <- function(mu, phi) {
  sd <- sqrt(mu + ((mu^2)/phi))
  return(sd)
}
```

```{r}
library(MASS)
# Năm 2016
tcm2016 <- subset(df_tcm, nam == "2016")
m_tcm16 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2016)
summary(m_tcm16)
theta <- 4.229
beta <- 0.016
gamma1 <- -0.170
gamma2 <- -0.007
phi <- 15.109

tcm2016$mu <- getmu(t = tcm2016$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = tcm2016, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2017
tcm2017 <- subset(df_tcm, nam == "2017")
m_tcm17 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2017)
summary(m_tcm17)
theta <- 5.488
beta <- 0.008
gamma1 <- -0.520
gamma2 <- -0.708
phi <- 35.945

tcm2017$mu <- getmu(t = tcm2017$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = tcm2017, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()

```

```{r}
## Năm 2019
tcm2019 <- subset(df_tcm, nam == "2019")
m_tcm19 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2019)
summary(m_tcm19)
theta <- 5.999
beta <- -0.0002
gamma1 <- 0.059
gamma2 <- -1.110
phi <- 9.736

tcm2019$mu <- getmu(t = tcm2019$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = tcm2019, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2020
tcm2020 <- subset(df_tcm, nam == "2020")
m_tcm20 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2020)
summary(m_tcm20)
theta <- 5.286
beta <- -0.001
gamma1 <- 0.721
gamma2 <- -2.065
phi <- 5.920

tcm2020$mu <- getmu(t = tcm2020$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = tcm2020, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()

```

```{r}
## Năm 2022
tcm2022 <- subset(df_tcm, nam == "2022")
m_tcm22 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2022)
summary(m_tcm22)
theta <- -25.757
beta <- 0.130
gamma1 <- -2.124
gamma2 <- -0.469
phi <- 3.418

tcm2022$mu <- getmu(t = tcm2022$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = tcm2022, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
## Năm 2024
tcm2024 <- subset(df_tcm, nam == "2024")
m_tcm24 <- glm.nb(total ~ t + I(cos(2*pi*t/52)) + 
                  I(sin(2*pi*t/52)),
                data = tcm2024)
summary(m_tcm24)
theta <- 13.367
beta <- -0.028
gamma1 <- -0.902
gamma2 <- -0.460
phi <- 8.160

tcm2024$mu <- getmu(t = tcm2024$t, theta = theta, beta = beta,  m = 1, gamma1 = gamma1, gamma2 = gamma2)

ggplot(data = tcm2024, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 52, by = 4)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw()
```

```{r}
df_tcm$mu <- bind_rows(
  tcm2016 %>% dplyr::select(mu),
  tcm2017 %>% dplyr::select(mu),
  tcm2019 %>% dplyr::select(mu),
  tcm2020 %>% dplyr::select(mu),
  tcm2022 %>% dplyr::select(mu),
  tcm2024 %>% dplyr::select(mu)
) %>% pull(mu)

g2 <- ggplot(data = df_tcm, aes(x = t, y = total)) +
  geom_point() +
  geom_line(aes(y = mu), col = "blue") +
  geom_vline(xintercept = 52 * c(1:6), col = "red") +
  scale_x_continuous(name = "Tuần", breaks = seq(from = 1, to = 299, by = 26)) +
  scale_y_continuous(name = "Số ca trong tuần") +
  theme_bw() +
  annotate("text", x = 26, y = 2000, label = "2016") +
  annotate("text", x = 26*3, y = 2000, label = "2017") +
  annotate("text", x = 26*5, y = 2000, label = "2019") +
  annotate("text", x = 26*7, y = 2000, label = "2020") +
  annotate("text", x = 26*9, y = 2000, label = "2022") +
  annotate("text", x = 26*11, y = 2000, label = "2024")
```

```{r}
library(patchwork)
g2 / g1_tcm
```

```{r}
theta <- c(4.229, 5.488, 5.999, 5.286, -25.757)
beta <- c(0.016, 0.008, -0.0002, -0.001, 0.130)
gamma1 <- c(-0.170, -0.520, 0.059, 0.721, -2.124)
gamma2 <- c(-0.007, -0.708, -1.110, -2.065, -0.469)
phi <- c(15.109, 35.945, 9.736, 5.920, 3.418)
year <- c(2016, 2017, 2019, 2020, 2022)

dff <- data.frame(year, theta, beta, gamma1, gamma2, phi)
```